### ISSUE TITLE
New font file in Bootstrap 3.3.2

### ISSUE THREAD

**Issue by ZaLiTHkA** [dbtek/bootswatch-dist#2]
Noticed an issue while including `3.3.2-yeti` in a new app mockup this morning, in which my browser was complaining about not being able to load a `woff2` font file. As it turns out, Bootstrap now includes a [new font file](https://github.com/twbs/bootstrap/pull/13871).

For my projects, I'm quite happy to stick with 3.3.0 for the moment (before the new font format), just figured I'd log this one here for your reference. :)

**Comment by dbtek** [comment]
Thanks @ZaLiTHkA,

I was not aware of this. New fonts are not included in bootswatch-dist. This should be fixed ASAP.
