### ISSUE TITLE
Grunt ignores bootswatch

### ISSUE THREAD

**Issue by heathyates** [dbtek/bootswatch-dist#21]
My gruntfile ignores the dependency in bower and does not install bootswatch-dist. I am able to install other bower components such as jquery, jquery-ui, and etc. Since the only dependency that will not install into my application wwwroot folder is bootswatch, I feel it merits investigation. 

Here are the steps to reproduce my problem: 

Basic Steps 
0. Obtain [CTP6](https://www.visualstudio.com/en-us/news/vs2015-vs.aspx)
1. You can use commandline in windows and not CTP6 if you wish. See [how](http://blogs.msdn.com/b/webdev/archive/2015/02/28/asp-net-yeoman-generators-for-beta-3.aspx)
2. Make sure basic empty application or you can use my open source project [here](https://github.com/HeathWillCode/SampleLibrary). 

How to reproduce problem. Open the commandline of your choice and go to the project root directory. 
1. bower init 
2. npm install grunt -save 
3. npm install grunt-bower-task -save 
4. grunt 

What you should see is something like I have outlined [here](http://stackoverflow.com/questions/28839764/how-can-i-get-bootswatch-theme-to-work-with-my-gruntfile-js) 

Thanks.

**Comment by dbtek** [comment]
I don't know anything about grunt-bower-task. If you use it to wire dependencies in html, I suggest you to use [grunt-wiredep](https://github.com/stephenplusplus/grunt-wiredep). It perfectly wires bootswatch-dist.

**Comment by heathyates** [comment]
Thanks for your reply. 

I am new to this myself, but I use grunt-bower-task and invoke it with a node package manager command (npm). So something like npm install grunt-bower-task -save, and then I have it reside in the gruntfile.js. What I mean by all this is to bring the dependency into the wwwroot of the application. Only after it is brought into wwwroot do I make a reference to it in the html (which I can't because it doesn't work). 

My temporary workaround is to use thomaspark/bootswatch with the above process I gave (steps 1-4), but I feel your approach is superior as it allows specific dependencies to be brought in. Unfortunately, I doubt we can determine the cause. 

Since I found a workaround, I will go ahead and close this issue, but if you start looking into grunt-bower-task in the future for your repo. Please let me know here.

**Comment by dbtek** [comment]
If it is all about installing bower_components in different directory you should be using `.bowerrc` file. Take a look at [docs](http://bower.io/docs/config/).
