### ISSUE TITLE
Feature request :) Be able to install several themes

### ISSUE THREAD

**Issue by akuz** [dbtek/bootswatch-dist#22]
It would be nice to be able to install several themes in one project :)
The idea I have is to use different themes for different parts of the page.
For this, it would be necessary to wrap the bootstrap theme CSS like:

    .flatly-theme {
      /* bootstrap here */
    }

Just a suggestion :)

**Comment by dbtek** [comment]
Hi @akuz,
It's not related to boostwatch-dist. You want to add a feature to all bootswatch themes.
