### ISSUE TITLE
Keeping up2date with bower

### ISSUE THREAD

**Issue by IngwiePhoenix** [dbtek/bootswatch-dist#23]
Hey.

What is the right way to always use the latest version for a specific dist? I am trying to match every 3.x.x version for the -cyborg theme; however, bower always insists on installing `bootswatch-dist#3.3.1+2-readable`... So I have to use `#3.3.4-cyborg` for now.

Kind regards, Ingwie

**Comment by dbtek** [comment]
Hey @IngwiePhoenix,

Sorry, I thought I replied your comment. I don't know where it is gone. There is unfortunately no way to match latest minor semver of a theme.

There are two ways of declaring a version of a theme: tag name or branch name. You can only install a specific version or latest version of a theme respectively.
