### ISSUE TITLE
include .less files

### ISSUE THREAD

**Issue by FreakinaBox** [dbtek/bootswatch-dist#24]
include .less files please

**Comment by dbtek** [comment]
I think you should be using [bootswatch](https://github.com/thomaspark/bootswatch/) for source files instead of bootswatch-dist. Am I wrong?

**Comment by FreakinaBox** [comment]
going strait to bootswatch doesn't allow me to include a specific theme in my dependency manager like your great setup does.
My reason for requesting the less files is that i want to include a theme the way you do here, I also want to maintain the ability to use the bootstrap mixins and variables in my less files for my project. this would also allow me to tweak your themes without having to directly modify your files.
