### ISSUE TITLE
bower.json's `main` should not contain any font files

### ISSUE THREAD

**Issue by cvrebert** [dbtek/bootswatch-dist#25]
See https://github.com/bower/bower.json-spec/commit/0b34d2bb0bdd4fa31fa9728f787f49e170e41f99#diff-04c6e90faac2675aa89e2176d2eec7d8R87 and https://github.com/twbs/bootstrap/commit/6cb9d6ce015f5a986974121799daf264441bbe5f

**Comment by dbtek** [comment]
This was fixed with [b33ac23](https://github.com/dbtek/bootswatch-dist/commit/b33ac23cf97e453a40c908180a8666830a688544).
