### ISSUE TITLE
Bootswatch-dist is missing the font files in "main" attribute

### ISSUE THREAD

**Issue by renato** [dbtek/bootswatch-dist#4]
`bower.json` "main" attribute is missing the fonts.

These fonts are present in the official bootstrap bower.json.

In bootswatch-dist's bower.json, these are the missing lines:
```
"fonts/glyphicons-halflings-regular.eot",
"fonts/glyphicons-halflings-regular.svg",
"fonts/glyphicons-halflings-regular.ttf",
"fonts/glyphicons-halflings-regular.woff",
"fonts/glyphicons-halflings-regular.woff2"
```

**Comment by dbtek** [comment]
Bower cache cleaning is required if latest version is cached to see font files in main property.
```bash
$ bower cache clean bootswatch-dist
```

**Comment by renato** [comment]
Thank you and sorry for the flood.

**Comment by dbtek** [comment]
no problem :smile:
